name: bajo_flutterapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'  # Remove this line if you want to publish to pub.dev

# Version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_riverpod: ^2.0.0
  intl: ^0.18.0  # Correct version of intl package
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # Define the assets under the `flutter` section
  assets:
    - assets/images/track.png
    - assets/images/edit.png
    - assets/images/history.png
    - assets/images/create.png
    - assets/images/purple.jpg

  # Add fonts here
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

  # Material design icons
  uses-material-design: true
